# Generated by Django 5.1 on 2024-08-08 08:52

import datetime
import django.db.models.deletion
import farm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='inventory',
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_number',
            field=models.CharField(default=farm.models.generate_default_batch_number, max_length=50),
        ),
        migrations.AddField(
            model_name='batch',
            name='date_received',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inventory',
            name='last_updated',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=farm.models.generate_default_order_number, max_length=50),
        ),
        migrations.AddField(
            model_name='reward',
            name='expiry_date',
            field=models.DateField(default=farm.models.generate_default_expiry_date),
        ),
        migrations.AddField(
            model_name='reward',
            name='remaining_reward_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reward',
            name='reward_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='farm.customer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_number',
            field=models.CharField(default=farm.models.generate_default_sale_number, max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='batch',
            name='hatch_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='batch',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='day_old',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='twenty_one_day_old',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='week_old',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='farm.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='average_hatch_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_info',
            field=models.TextField(default=''),
        ),
    ]
